//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_FUNSAILMEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boat
    {
        public int Id { get; set; }
        public string BoatName { get; set; }
        public string BoatType { get; set; }
        public string Year { get; set; }
        public string Colour { get; set; }
        public string Capacity { get; set; }
        public int BoatOwnerId { get; set; }
        public int PierId { get; set; }
    }
}
