//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_FUNSAILMEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string CustomerId { get; set; }
        public int BoatId { get; set; }
        public string Review { get; set; }
        public bool Complete { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Boat Boat { get; set; }
    }
}
