//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_FUNSAILMEL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FUNSAILMEL_Model1Container : DbContext
    {
        public FUNSAILMEL_Model1Container()
            : base("name=FUNSAILMEL_Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<BoatOwner> BoatOwners { get; set; }
        public virtual DbSet<Boat> Boats { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Pier> Piers { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
    }
}
